# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dispatch/security/v1/security.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#dispatch/security/v1/security.proto\x12\x14\x64ispatch.security.v1"\x8c\x01\n\x14NetworkAccessControl\x12\x39\n\x05\x61llow\x18\x01 \x03(\x0b\x32#.dispatch.security.v1.NetworkPrefixR\x05\x61llow\x12\x39\n\x05\x62lock\x18\x02 \x03(\x0b\x32#.dispatch.security.v1.NetworkPrefixR\x05\x62lock"7\n\rNetworkPrefix\x12\x12\n\x04\x61\x64\x64r\x18\x01 \x01(\x0cR\x04\x61\x64\x64r\x12\x12\n\x04\x62its\x18\x02 \x01(\rR\x04\x62itsB\x9b\x01\n\x18\x63om.dispatch.security.v1B\rSecurityProtoP\x01\xa2\x02\x03\x44SX\xaa\x02\x14\x44ispatch.Security.V1\xca\x02\x14\x44ispatch\\Security\\V1\xe2\x02 Dispatch\\Security\\V1\\GPBMetadata\xea\x02\x16\x44ispatch::Security::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "dispatch.security.v1.security_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n\030com.dispatch.security.v1B\rSecurityProtoP\001\242\002\003DSX\252\002\024Dispatch.Security.V1\312\002\024Dispatch\\Security\\V1\342\002 Dispatch\\Security\\V1\\GPBMetadata\352\002\026Dispatch::Security::V1"
    )
    _globals["_NETWORKACCESSCONTROL"]._serialized_start = 62
    _globals["_NETWORKACCESSCONTROL"]._serialized_end = 202
    _globals["_NETWORKPREFIX"]._serialized_start = 204
    _globals["_NETWORKPREFIX"]._serialized_end = 259
# @@protoc_insertion_point(module_scope)
