# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ring/task/v1/service.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ring.record.v1 import record_pb2 as ring_dot_record_dot_v1_dot_record__pb2
from ring.task.v1 import config_pb2 as ring_dot_task_dot_v1_dot_config__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1aring/task/v1/service.proto\x12\x0cring.task.v1\x1a\x1bring/record/v1/record.proto\x1a\x19ring/task/v1/config.proto\x1a\x19google/protobuf/any.proto"\xc2\x01\n\x0f\x43reateTaskInput\x12#\n\rcoroutine_uri\x18\x01 \x01(\tR\x0c\x63oroutineUri\x12*\n\x05input\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyR\x05input\x12,\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x14.ring.task.v1.ConfigR\x06\x63onfig\x12\x30\n\x08metadata\x18\x04 \x01(\x0b\x32\x14.google.protobuf.AnyR\x08metadata"d\n\x10\x43reateTaskOutput\x12,\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x14.ring.task.v1.ConfigR\x06\x63onfig\x12"\n\x02id\x18\x02 \x01(\x0b\x32\x12.ring.record.v1.IDR\x02id"I\n\x12\x43reateTasksRequest\x12\x33\n\x05tasks\x18\x01 \x03(\x0b\x32\x1d.ring.task.v1.CreateTaskInputR\x05tasks"K\n\x13\x43reateTasksResponse\x12\x34\n\x05tasks\x18\x01 \x03(\x0b\x32\x1e.ring.task.v1.CreateTaskOutputR\x05tasks2_\n\x07Service\x12T\n\x0b\x43reateTasks\x12 .ring.task.v1.CreateTasksRequest\x1a!.ring.task.v1.CreateTasksResponse"\x00\x42r\n\x10\x63om.ring.task.v1B\x0cServiceProtoP\x01\xa2\x02\x03RTX\xaa\x02\x0cRing.Task.V1\xca\x02\x0cRing\\Task\\V1\xe2\x02\x18Ring\\Task\\V1\\GPBMetadata\xea\x02\x0eRing::Task::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "ring.task.v1.service_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n\020com.ring.task.v1B\014ServiceProtoP\001\242\002\003RTX\252\002\014Ring.Task.V1\312\002\014Ring\\Task\\V1\342\002\030Ring\\Task\\V1\\GPBMetadata\352\002\016Ring::Task::V1"
    )
    _globals["_CREATETASKINPUT"]._serialized_start = 128
    _globals["_CREATETASKINPUT"]._serialized_end = 322
    _globals["_CREATETASKOUTPUT"]._serialized_start = 324
    _globals["_CREATETASKOUTPUT"]._serialized_end = 424
    _globals["_CREATETASKSREQUEST"]._serialized_start = 426
    _globals["_CREATETASKSREQUEST"]._serialized_end = 499
    _globals["_CREATETASKSRESPONSE"]._serialized_start = 501
    _globals["_CREATETASKSRESPONSE"]._serialized_end = 576
    _globals["_SERVICE"]._serialized_start = 578
    _globals["_SERVICE"]._serialized_end = 673
# @@protoc_insertion_point(module_scope)
