from types import FrameType
from typing import Any, Generator, Tuple

def get_frame_ip(frame: FrameType | Generator) -> int: ...
def set_frame_ip(frame: FrameType | Generator, ip: int): ...
def get_frame_sp(frame: FrameType | Generator) -> int: ...
def set_frame_sp(frame: FrameType | Generator, sp: int): ...
def get_frame_stack_at(
    frame: FrameType | Generator, index: int
) -> Tuple[bool, Any]: ...
def set_frame_stack_at(
    frame: FrameType | Generator, index: int, unset: bool, value: Any
): ...
def get_generator_frame_state(frame: FrameType | Generator) -> int: ...
def set_generator_frame_state(frame: FrameType | Generator, state: int): ...
