from types import FrameType
from typing import Any, AsyncGenerator, Coroutine, Generator, Tuple

def get_frame_ip(frame: FrameType | Coroutine | Generator | AsyncGenerator) -> int: ...
def set_frame_ip(
    frame: FrameType | Coroutine | Generator | AsyncGenerator, ip: int
): ...
def get_frame_sp(frame: FrameType | Coroutine | Generator | AsyncGenerator) -> int: ...
def set_frame_sp(
    frame: FrameType | Coroutine | Generator | AsyncGenerator, sp: int
): ...
def get_frame_stack_at(
    frame: FrameType | Coroutine | Generator | AsyncGenerator, index: int
) -> Tuple[bool, Any]: ...
def set_frame_stack_at(
    frame: FrameType | Coroutine | Generator | AsyncGenerator,
    index: int,
    unset: bool,
    value: Any,
): ...
def get_frame_state(
    frame: FrameType | Coroutine | Generator | AsyncGenerator,
) -> int: ...
def set_frame_state(
    frame: FrameType | Coroutine | Generator | AsyncGenerator, state: int
): ...
