# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dispatch/sdk/python/v1/pickled.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$dispatch/sdk/python/v1/pickled.proto\x12\x16\x64ispatch.sdk.python.v1".\n\x07Pickled\x12#\n\rpickled_value\x18\x01 \x01(\x0cR\x0cpickledValueB\xa5\x01\n\x1a\x63om.dispatch.sdk.python.v1B\x0cPickledProtoP\x01\xa2\x02\x03\x44SP\xaa\x02\x16\x44ispatch.Sdk.Python.V1\xca\x02\x16\x44ispatch\\Sdk\\Python\\V1\xe2\x02"Dispatch\\Sdk\\Python\\V1\\GPBMetadata\xea\x02\x19\x44ispatch::Sdk::Python::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "dispatch.sdk.python.v1.pickled_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b'\n\032com.dispatch.sdk.python.v1B\014PickledProtoP\001\242\002\003DSP\252\002\026Dispatch.Sdk.Python.V1\312\002\026Dispatch\\Sdk\\Python\\V1\342\002"Dispatch\\Sdk\\Python\\V1\\GPBMetadata\352\002\031Dispatch::Sdk::Python::V1'
    )
    _globals["_PICKLED"]._serialized_start = 64
    _globals["_PICKLED"]._serialized_end = 110
# @@protoc_insertion_point(module_scope)
