# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dispatch/sdk/v1/endpoint.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1e\x64ispatch/sdk/v1/endpoint.proto\x12\x0f\x64ispatch.sdk.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto"U\n\x17\x43reateExecutionsRequest\x12:\n\nexecutions\x18\x01 \x03(\x0b\x32\x1a.dispatch.sdk.v1.ExecutionR\nexecutions",\n\x18\x43reateExecutionsResponse\x12\x10\n\x03ids\x18\x01 \x03(\tR\x03ids"\xc4\x01\n\tExecution\x12#\n\rcoroutine_uri\x18\x01 \x01(\tR\x0c\x63oroutineUri\x12+\n\x11\x63oroutine_version\x18\x02 \x01(\tR\x10\x63oroutineVersion\x12*\n\x05input\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyR\x05input\x12\x39\n\nexpiration\x18\x04 \x01(\x0b\x32\x19.google.protobuf.DurationR\nexpiration2|\n\x0f\x45ndpointService\x12i\n\x10\x43reateExecutions\x12(.dispatch.sdk.v1.CreateExecutionsRequest\x1a).dispatch.sdk.v1.CreateExecutionsResponse"\x00\x42\x82\x01\n\x13\x63om.dispatch.sdk.v1B\rEndpointProtoP\x01\xa2\x02\x03\x44SX\xaa\x02\x0f\x44ispatch.Sdk.V1\xca\x02\x0f\x44ispatch\\Sdk\\V1\xe2\x02\x1b\x44ispatch\\Sdk\\V1\\GPBMetadata\xea\x02\x11\x44ispatch::Sdk::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "dispatch.sdk.v1.endpoint_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n\023com.dispatch.sdk.v1B\rEndpointProtoP\001\242\002\003DSX\252\002\017Dispatch.Sdk.V1\312\002\017Dispatch\\Sdk\\V1\342\002\033Dispatch\\Sdk\\V1\\GPBMetadata\352\002\021Dispatch::Sdk::V1"
    )
    _globals["_CREATEEXECUTIONSREQUEST"]._serialized_start = 110
    _globals["_CREATEEXECUTIONSREQUEST"]._serialized_end = 195
    _globals["_CREATEEXECUTIONSRESPONSE"]._serialized_start = 197
    _globals["_CREATEEXECUTIONSRESPONSE"]._serialized_end = 241
    _globals["_EXECUTION"]._serialized_start = 244
    _globals["_EXECUTION"]._serialized_end = 440
    _globals["_ENDPOINTSERVICE"]._serialized_start = 442
    _globals["_ENDPOINTSERVICE"]._serialized_end = 566
# @@protoc_insertion_point(module_scope)
