# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from dispatch.sdk.v1 import executor_pb2 as dispatch_dot_sdk_dot_v1_dot_executor__pb2


class ExecutorServiceStub(object):
    """The Executor service is used to execute coroutines remotely."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
            "/dispatch.sdk.v1.ExecutorService/Execute",
            request_serializer=dispatch_dot_sdk_dot_v1_dot_executor__pb2.ExecuteRequest.SerializeToString,
            response_deserializer=dispatch_dot_sdk_dot_v1_dot_executor__pb2.ExecuteResponse.FromString,
        )


class ExecutorServiceServicer(object):
    """The Executor service is used to execute coroutines remotely."""

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Execute": grpc.unary_unary_rpc_method_handler(
            servicer.Execute,
            request_deserializer=dispatch_dot_sdk_dot_v1_dot_executor__pb2.ExecuteRequest.FromString,
            response_serializer=dispatch_dot_sdk_dot_v1_dot_executor__pb2.ExecuteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "dispatch.sdk.v1.ExecutorService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ExecutorService(object):
    """The Executor service is used to execute coroutines remotely."""

    @staticmethod
    def Execute(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/dispatch.sdk.v1.ExecutorService/Execute",
            dispatch_dot_sdk_dot_v1_dot_executor__pb2.ExecuteRequest.SerializeToString,
            dispatch_dot_sdk_dot_v1_dot_executor__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
