# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dispatch/sdk/v1/function.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

from dispatch.sdk.v1 import exit_pb2 as dispatch_dot_sdk_dot_v1_dot_exit__pb2
from dispatch.sdk.v1 import poll_pb2 as dispatch_dot_sdk_dot_v1_dot_poll__pb2
from dispatch.sdk.v1 import status_pb2 as dispatch_dot_sdk_dot_v1_dot_status__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1e\x64ispatch/sdk/v1/function.proto\x12\x0f\x64ispatch.sdk.v1\x1a\x1a\x64ispatch/sdk/v1/exit.proto\x1a\x1a\x64ispatch/sdk/v1/poll.proto\x1a\x1c\x64ispatch/sdk/v1/status.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xa2\x03\n\nRunRequest\x12\x1a\n\x08\x66unction\x18\x01 \x01(\tR\x08\x66unction\x12,\n\x05input\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00R\x05input\x12>\n\x0bpoll_result\x18\x03 \x01(\x0b\x32\x1b.dispatch.sdk.v1.PollResultH\x00R\npollResult\x12\x1f\n\x0b\x64ispatch_id\x18\x04 \x01(\tR\ndispatchId\x12,\n\x12parent_dispatch_id\x18\x05 \x01(\tR\x10parentDispatchId\x12(\n\x10root_dispatch_id\x18\x06 \x01(\tR\x0erootDispatchId\x12?\n\rcreation_time\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0c\x63reationTime\x12\x43\n\x0f\x65xpiration_time\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0e\x65xpirationTimeB\x0b\n\tdirective"\xa5\x01\n\x0bRunResponse\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x17.dispatch.sdk.v1.StatusR\x06status\x12+\n\x04\x65xit\x18\x02 \x01(\x0b\x32\x15.dispatch.sdk.v1.ExitH\x00R\x04\x65xit\x12+\n\x04poll\x18\x03 \x01(\x0b\x32\x15.dispatch.sdk.v1.PollH\x00R\x04pollB\x0b\n\tdirective2U\n\x0f\x46unctionService\x12\x42\n\x03Run\x12\x1b.dispatch.sdk.v1.RunRequest\x1a\x1c.dispatch.sdk.v1.RunResponse"\x00\x42\x82\x01\n\x13\x63om.dispatch.sdk.v1B\rFunctionProtoP\x01\xa2\x02\x03\x44SX\xaa\x02\x0f\x44ispatch.Sdk.V1\xca\x02\x0f\x44ispatch\\Sdk\\V1\xe2\x02\x1b\x44ispatch\\Sdk\\V1\\GPBMetadata\xea\x02\x11\x44ispatch::Sdk::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "dispatch.sdk.v1.function_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n\023com.dispatch.sdk.v1B\rFunctionProtoP\001\242\002\003DSX\252\002\017Dispatch.Sdk.V1\312\002\017Dispatch\\Sdk\\V1\342\002\033Dispatch\\Sdk\\V1\\GPBMetadata\352\002\021Dispatch::Sdk::V1"
    )
    _globals["_RUNREQUEST"]._serialized_start = 198
    _globals["_RUNREQUEST"]._serialized_end = 616
    _globals["_RUNRESPONSE"]._serialized_start = 619
    _globals["_RUNRESPONSE"]._serialized_end = 784
    _globals["_FUNCTIONSERVICE"]._serialized_start = 786
    _globals["_FUNCTIONSERVICE"]._serialized_end = 871
# @@protoc_insertion_point(module_scope)
