# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dispatch/sdk/v1/key.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19\x64ispatch/sdk/v1/key.proto\x12\x0f\x64ispatch.sdk.v1"\x19\n\x17\x43reateSigningKeyRequest"I\n\x18\x43reateSigningKeyResponse\x12-\n\x03key\x18\x01 \x01(\x0b\x32\x1b.dispatch.sdk.v1.SigningKeyR\x03key"\x19\n\x17\x44\x65leteSigningKeyRequest"\x1a\n\x18\x44\x65leteSigningKeyResponse"\x18\n\x16ListSigningKeysRequest"J\n\x17ListSigningKeysResponse\x12/\n\x04keys\x18\x01 \x03(\x0b\x32\x1b.dispatch.sdk.v1.SigningKeyR\x04keys"4\n\nSigningKey\x12\x1f\n\npublic_key\x18\x02 \x01(\x0cH\x00R\tpublicKeyB\x05\n\x03key2\xcb\x02\n\x11SigningKeyService\x12g\n\x10\x43reateSigningKey\x12(.dispatch.sdk.v1.CreateSigningKeyRequest\x1a).dispatch.sdk.v1.CreateSigningKeyResponse\x12g\n\x10\x44\x65leteSigningKey\x12(.dispatch.sdk.v1.DeleteSigningKeyRequest\x1a).dispatch.sdk.v1.DeleteSigningKeyResponse\x12\x64\n\x0fListSigningKeys\x12\'.dispatch.sdk.v1.ListSigningKeysRequest\x1a(.dispatch.sdk.v1.ListSigningKeysResponseB}\n\x13\x63om.dispatch.sdk.v1B\x08KeyProtoP\x01\xa2\x02\x03\x44SX\xaa\x02\x0f\x44ispatch.Sdk.V1\xca\x02\x0f\x44ispatch\\Sdk\\V1\xe2\x02\x1b\x44ispatch\\Sdk\\V1\\GPBMetadata\xea\x02\x11\x44ispatch::Sdk::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "dispatch.sdk.v1.key_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n\023com.dispatch.sdk.v1B\010KeyProtoP\001\242\002\003DSX\252\002\017Dispatch.Sdk.V1\312\002\017Dispatch\\Sdk\\V1\342\002\033Dispatch\\Sdk\\V1\\GPBMetadata\352\002\021Dispatch::Sdk::V1"
    )
    _globals["_CREATESIGNINGKEYREQUEST"]._serialized_start = 46
    _globals["_CREATESIGNINGKEYREQUEST"]._serialized_end = 71
    _globals["_CREATESIGNINGKEYRESPONSE"]._serialized_start = 73
    _globals["_CREATESIGNINGKEYRESPONSE"]._serialized_end = 146
    _globals["_DELETESIGNINGKEYREQUEST"]._serialized_start = 148
    _globals["_DELETESIGNINGKEYREQUEST"]._serialized_end = 173
    _globals["_DELETESIGNINGKEYRESPONSE"]._serialized_start = 175
    _globals["_DELETESIGNINGKEYRESPONSE"]._serialized_end = 201
    _globals["_LISTSIGNINGKEYSREQUEST"]._serialized_start = 203
    _globals["_LISTSIGNINGKEYSREQUEST"]._serialized_end = 227
    _globals["_LISTSIGNINGKEYSRESPONSE"]._serialized_start = 229
    _globals["_LISTSIGNINGKEYSRESPONSE"]._serialized_end = 303
    _globals["_SIGNINGKEY"]._serialized_start = 305
    _globals["_SIGNINGKEY"]._serialized_end = 357
    _globals["_SIGNINGKEYSERVICE"]._serialized_start = 360
    _globals["_SIGNINGKEYSERVICE"]._serialized_end = 691
# @@protoc_insertion_point(module_scope)
