# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from dispatch.sdk.v1 import key_pb2 as dispatch_dot_sdk_dot_v1_dot_key__pb2


class SigningKeyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSigningKey = channel.unary_unary(
            "/dispatch.sdk.v1.SigningKeyService/CreateSigningKey",
            request_serializer=dispatch_dot_sdk_dot_v1_dot_key__pb2.CreateSigningKeyRequest.SerializeToString,
            response_deserializer=dispatch_dot_sdk_dot_v1_dot_key__pb2.CreateSigningKeyResponse.FromString,
        )
        self.DeleteSigningKey = channel.unary_unary(
            "/dispatch.sdk.v1.SigningKeyService/DeleteSigningKey",
            request_serializer=dispatch_dot_sdk_dot_v1_dot_key__pb2.DeleteSigningKeyRequest.SerializeToString,
            response_deserializer=dispatch_dot_sdk_dot_v1_dot_key__pb2.DeleteSigningKeyResponse.FromString,
        )
        self.ListSigningKeys = channel.unary_unary(
            "/dispatch.sdk.v1.SigningKeyService/ListSigningKeys",
            request_serializer=dispatch_dot_sdk_dot_v1_dot_key__pb2.ListSigningKeysRequest.SerializeToString,
            response_deserializer=dispatch_dot_sdk_dot_v1_dot_key__pb2.ListSigningKeysResponse.FromString,
        )


class SigningKeyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSigningKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteSigningKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListSigningKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SigningKeyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateSigningKey": grpc.unary_unary_rpc_method_handler(
            servicer.CreateSigningKey,
            request_deserializer=dispatch_dot_sdk_dot_v1_dot_key__pb2.CreateSigningKeyRequest.FromString,
            response_serializer=dispatch_dot_sdk_dot_v1_dot_key__pb2.CreateSigningKeyResponse.SerializeToString,
        ),
        "DeleteSigningKey": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteSigningKey,
            request_deserializer=dispatch_dot_sdk_dot_v1_dot_key__pb2.DeleteSigningKeyRequest.FromString,
            response_serializer=dispatch_dot_sdk_dot_v1_dot_key__pb2.DeleteSigningKeyResponse.SerializeToString,
        ),
        "ListSigningKeys": grpc.unary_unary_rpc_method_handler(
            servicer.ListSigningKeys,
            request_deserializer=dispatch_dot_sdk_dot_v1_dot_key__pb2.ListSigningKeysRequest.FromString,
            response_serializer=dispatch_dot_sdk_dot_v1_dot_key__pb2.ListSigningKeysResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "dispatch.sdk.v1.SigningKeyService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class SigningKeyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSigningKey(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/dispatch.sdk.v1.SigningKeyService/CreateSigningKey",
            dispatch_dot_sdk_dot_v1_dot_key__pb2.CreateSigningKeyRequest.SerializeToString,
            dispatch_dot_sdk_dot_v1_dot_key__pb2.CreateSigningKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DeleteSigningKey(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/dispatch.sdk.v1.SigningKeyService/DeleteSigningKey",
            dispatch_dot_sdk_dot_v1_dot_key__pb2.DeleteSigningKeyRequest.SerializeToString,
            dispatch_dot_sdk_dot_v1_dot_key__pb2.DeleteSigningKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListSigningKeys(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/dispatch.sdk.v1.SigningKeyService/ListSigningKeys",
            dispatch_dot_sdk_dot_v1_dot_key__pb2.ListSigningKeysRequest.SerializeToString,
            dispatch_dot_sdk_dot_v1_dot_key__pb2.ListSigningKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
