# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dispatch/http/v1/http.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dispatch.security.v1 import security_pb2 as dispatch_dot_security_dot_v1_dot_security__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x64ispatch/http/v1/http.proto\x12\x10\x64ispatch.http.v1\x1a#dispatch/security/v1/security.proto\"\xdb\x01\n\x07Request\x12\x16\n\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n\x03url\x18\x02 \x01(\tR\x03url\x12\x30\n\x06header\x18\x04 \x03(\x0b\x32\x18.dispatch.http.v1.HeaderR\x06header\x12\x12\n\x04\x62ody\x18\x03 \x01(\x0cR\x04\x62ody\x12`\n\x16network_access_control\x18\x05 \x01(\x0b\x32*.dispatch.security.v1.NetworkAccessControlR\x14networkAccessControl\"q\n\x08Response\x12\x1f\n\x0bstatus_code\x18\x01 \x01(\x05R\nstatusCode\x12\x30\n\x06header\x18\x02 \x03(\x0b\x32\x18.dispatch.http.v1.HeaderR\x06header\x12\x12\n\x04\x62ody\x18\x03 \x01(\x0cR\x04\x62ody\"2\n\x06Header\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n\x05value\x18\x02 \x01(\tR\x05valueB\x83\x01\n\x14\x63om.dispatch.http.v1B\tHttpProtoP\x01\xa2\x02\x03\x44HX\xaa\x02\x10\x44ispatch.Http.V1\xca\x02\x10\x44ispatch\\Http\\V1\xe2\x02\x1c\x44ispatch\\Http\\V1\\GPBMetadata\xea\x02\x12\x44ispatch::Http::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dispatch.http.v1.http_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.dispatch.http.v1B\tHttpProtoP\001\242\002\003DHX\252\002\020Dispatch.Http.V1\312\002\020Dispatch\\Http\\V1\342\002\034Dispatch\\Http\\V1\\GPBMetadata\352\002\022Dispatch::Http::V1'
  _globals['_REQUEST']._serialized_start=87
  _globals['_REQUEST']._serialized_end=306
  _globals['_RESPONSE']._serialized_start=308
  _globals['_RESPONSE']._serialized_end=421
  _globals['_HEADER']._serialized_start=423
  _globals['_HEADER']._serialized_end=473
# @@protoc_insertion_point(module_scope)
