# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dispatch/v1/metadata.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x64ispatch/v1/metadata.proto\x12\x0b\x64ispatch.v1\"J\n\x08Metadata\x12\'\n\x0forganization_id\x18\x01 \x01(\rR\x0eorganizationId\x12\x15\n\x06key_id\x18\x02 \x01(\rR\x05keyIdBm\n\x0f\x63om.dispatch.v1B\rMetadataProtoP\x01\xa2\x02\x03\x44XX\xaa\x02\x0b\x44ispatch.V1\xca\x02\x0b\x44ispatch\\V1\xe2\x02\x17\x44ispatch\\V1\\GPBMetadata\xea\x02\x0c\x44ispatch::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dispatch.v1.metadata_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.dispatch.v1B\rMetadataProtoP\001\242\002\003DXX\252\002\013Dispatch.V1\312\002\013Dispatch\\V1\342\002\027Dispatch\\V1\\GPBMetadata\352\002\014Dispatch::V1'
  _globals['_METADATA']._serialized_start=43
  _globals['_METADATA']._serialized_end=117
# @@protoc_insertion_point(module_scope)
