name: PyPI

on:
- push

jobs:
  build:
    name: build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - run: python -m pip install cibuildwheel==2.16.5
    - run: python -m cibuildwheel --output-dir wheelhouse
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: wheelhouse/*.whl

  test:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/dispatch-functions
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: *.whl
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://pypi.org/p/dispatch-functions
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: *.whl
    - uses: pypa/gh-action-pypi-publish@release/v1
