# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ring.admin.v1 import member_pb2 as ring_dot_admin_dot_v1_dot_member__pb2


class MemberServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MemberState = channel.unary_unary(
            "/ring.admin.v1.MemberService/MemberState",
            request_serializer=ring_dot_admin_dot_v1_dot_member__pb2.MemberStateRequest.SerializeToString,
            response_deserializer=ring_dot_admin_dot_v1_dot_member__pb2.MemberStateResponse.FromString,
        )


class MemberServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MemberState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MemberServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "MemberState": grpc.unary_unary_rpc_method_handler(
            servicer.MemberState,
            request_deserializer=ring_dot_admin_dot_v1_dot_member__pb2.MemberStateRequest.FromString,
            response_serializer=ring_dot_admin_dot_v1_dot_member__pb2.MemberStateResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ring.admin.v1.MemberService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class MemberService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MemberState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ring.admin.v1.MemberService/MemberState",
            ring_dot_admin_dot_v1_dot_member__pb2.MemberStateRequest.SerializeToString,
            ring_dot_admin_dot_v1_dot_member__pb2.MemberStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
